class SurahInfo {
  final int index;
  final String name;
  final String type; // مكية أو مدنية
  final int verseCount;

  const SurahInfo({
    required this.index,
    required this.name,
    required this.type,
    required this.verseCount,
  });

  int get number => index;
  int get totalVerses => verseCount;
}

typedef SurahMeta = SurahInfo;

class QuranSurahMeta {
  static const List<SurahInfo> surahs = [
    SurahInfo(index: 1, name: 'الفاتحة', type: 'مكية', verseCount: 7),
    SurahInfo(index: 2, name: 'البقرة', type: 'مدنية', verseCount: 286),
    SurahInfo(index: 3, name: 'آل عمران', type: 'مدنية', verseCount: 200),
    SurahInfo(index: 4, name: 'النساء', type: 'مدنية', verseCount: 176),
    SurahInfo(index: 5, name: 'المائدة', type: 'مدنية', verseCount: 120),
    SurahInfo(index: 6, name: 'الأنعام', type: 'مكية', verseCount: 165),
    SurahInfo(index: 7, name: 'الأعراف', type: 'مكية', verseCount: 206),
    SurahInfo(index: 8, name: 'الأنفال', type: 'مدنية', verseCount: 75),
    SurahInfo(index: 9, name: 'التوبة', type: 'مدنية', verseCount: 129),
    SurahInfo(index: 10, name: 'يونس', type: 'مكية', verseCount: 109),
    SurahInfo(index: 11, name: 'هود', type: 'مكية', verseCount: 123),
    SurahInfo(index: 12, name: 'يوسف', type: 'مكية', verseCount: 111),
    SurahInfo(index: 13, name: 'الرعد', type: 'مدنية', verseCount: 43),
    SurahInfo(index: 14, name: 'إبراهيم', type: 'مكية', verseCount: 52),
    SurahInfo(index: 15, name: 'الحجر', type: 'مكية', verseCount: 99),
    SurahInfo(index: 16, name: 'النحل', type: 'مكية', verseCount: 128),
    SurahInfo(index: 17, name: 'الإسراء', type: 'مكية', verseCount: 111),
    SurahInfo(index: 18, name: 'الكهف', type: 'مكية', verseCount: 110),
    SurahInfo(index: 19, name: 'مريم', type: 'مكية', verseCount: 98),
    SurahInfo(index: 20, name: 'طه', type: 'مكية', verseCount: 135),
    SurahInfo(index: 21, name: 'الأنبياء', type: 'مكية', verseCount: 112),
    SurahInfo(index: 22, name: 'الحج', type: 'مدنية', verseCount: 78),
    SurahInfo(index: 23, name: 'المؤمنون', type: 'مكية', verseCount: 118),
    SurahInfo(index: 24, name: 'النور', type: 'مدنية', verseCount: 64),
    SurahInfo(index: 25, name: 'الفرقان', type: 'مكية', verseCount: 77),
    SurahInfo(index: 26, name: 'الشعراء', type: 'مكية', verseCount: 227),
    SurahInfo(index: 27, name: 'النمل', type: 'مكية', verseCount: 93),
    SurahInfo(index: 28, name: 'القصص', type: 'مكية', verseCount: 88),
    SurahInfo(index: 29, name: 'العنكبوت', type: 'مكية', verseCount: 69),
    SurahInfo(index: 30, name: 'الروم', type: 'مكية', verseCount: 60),
    SurahInfo(index: 31, name: 'لقمان', type: 'مكية', verseCount: 34),
    SurahInfo(index: 32, name: 'السجدة', type: 'مكية', verseCount: 30),
    SurahInfo(index: 33, name: 'الأحزاب', type: 'مدنية', verseCount: 73),
    SurahInfo(index: 34, name: 'سبأ', type: 'مكية', verseCount: 54),
    SurahInfo(index: 35, name: 'فاطر', type: 'مكية', verseCount: 45),
    SurahInfo(index: 36, name: 'يس', type: 'مكية', verseCount: 83),
    SurahInfo(index: 37, name: 'الصافات', type: 'مكية', verseCount: 182),
    SurahInfo(index: 38, name: 'ص', type: 'مكية', verseCount: 88),
    SurahInfo(index: 39, name: 'الزمر', type: 'مكية', verseCount: 75),
    SurahInfo(index: 40, name: 'غافر', type: 'مكية', verseCount: 85),
    SurahInfo(index: 41, name: 'فصلت', type: 'مكية', verseCount: 54),
    SurahInfo(index: 42, name: 'الشورى', type: 'مكية', verseCount: 53),
    SurahInfo(index: 43, name: 'الزخرف', type: 'مكية', verseCount: 89),
    SurahInfo(index: 44, name: 'الدخان', type: 'مكية', verseCount: 59),
    SurahInfo(index: 45, name: 'الجاثية', type: 'مكية', verseCount: 37),
    SurahInfo(index: 46, name: 'الأحقاف', type: 'مكية', verseCount: 35),
    SurahInfo(index: 47, name: 'محمد', type: 'مدنية', verseCount: 38),
    SurahInfo(index: 48, name: 'الفتح', type: 'مدنية', verseCount: 29),
    SurahInfo(index: 49, name: 'الحجرات', type: 'مدنية', verseCount: 18),
    SurahInfo(index: 50, name: 'ق', type: 'مكية', verseCount: 45),
    SurahInfo(index: 51, name: 'الذاريات', type: 'مكية', verseCount: 60),
    SurahInfo(index: 52, name: 'الطور', type: 'مكية', verseCount: 49),
    SurahInfo(index: 53, name: 'النجم', type: 'مكية', verseCount: 62),
    SurahInfo(index: 54, name: 'القمر', type: 'مكية', verseCount: 55),
    SurahInfo(index: 55, name: 'الرحمن', type: 'مدنية', verseCount: 78),
    SurahInfo(index: 56, name: 'الواقعة', type: 'مكية', verseCount: 96),
    SurahInfo(index: 57, name: 'الحديد', type: 'مدنية', verseCount: 29),
    SurahInfo(index: 58, name: 'المجادلة', type: 'مدنية', verseCount: 22),
    SurahInfo(index: 59, name: 'الحشر', type: 'مدنية', verseCount: 24),
    SurahInfo(index: 60, name: 'الممتحنة', type: 'مدنية', verseCount: 13),
    SurahInfo(index: 61, name: 'الصف', type: 'مدنية', verseCount: 14),
    SurahInfo(index: 62, name: 'الجمعة', type: 'مدنية', verseCount: 11),
    SurahInfo(index: 63, name: 'المنافقون', type: 'مدنية', verseCount: 11),
    SurahInfo(index: 64, name: 'التغابن', type: 'مدنية', verseCount: 18),
    SurahInfo(index: 65, name: 'الطلاق', type: 'مدنية', verseCount: 12),
    SurahInfo(index: 66, name: 'التحريم', type: 'مدنية', verseCount: 12),
    SurahInfo(index: 67, name: 'الملك', type: 'مكية', verseCount: 30),
    SurahInfo(index: 68, name: 'القلم', type: 'مكية', verseCount: 52),
    SurahInfo(index: 69, name: 'الحاقة', type: 'مكية', verseCount: 52),
    SurahInfo(index: 70, name: 'المعارج', type: 'مكية', verseCount: 44),
    SurahInfo(index: 71, name: 'نوح', type: 'مكية', verseCount: 28),
    SurahInfo(index: 72, name: 'الجن', type: 'مكية', verseCount: 28),
    SurahInfo(index: 73, name: 'المزمل', type: 'مكية', verseCount: 20),
    SurahInfo(index: 74, name: 'المدثر', type: 'مكية', verseCount: 56),
    SurahInfo(index: 75, name: 'القيامة', type: 'مكية', verseCount: 40),
    SurahInfo(index: 76, name: 'الإنسان', type: 'مدنية', verseCount: 31),
    SurahInfo(index: 77, name: 'المرسلات', type: 'مكية', verseCount: 50),
    SurahInfo(index: 78, name: 'النبأ', type: 'مكية', verseCount: 40),
    SurahInfo(index: 79, name: 'النازعات', type: 'مكية', verseCount: 46),
    SurahInfo(index: 80, name: 'عبس', type: 'مكية', verseCount: 42),
    SurahInfo(index: 81, name: 'التكوير', type: 'مكية', verseCount: 29),
    SurahInfo(index: 82, name: 'الانفطار', type: 'مكية', verseCount: 19),
    SurahInfo(index: 83, name: 'المطففين', type: 'مكية', verseCount: 36),
    SurahInfo(index: 84, name: 'الانشقاق', type: 'مكية', verseCount: 25),
    SurahInfo(index: 85, name: 'البروج', type: 'مكية', verseCount: 22),
    SurahInfo(index: 86, name: 'الطارق', type: 'مكية', verseCount: 17),
    SurahInfo(index: 87, name: 'الأعلى', type: 'مكية', verseCount: 19),
    SurahInfo(index: 88, name: 'الغاشية', type: 'مكية', verseCount: 26),
    SurahInfo(index: 89, name: 'الفجر', type: 'مكية', verseCount: 30),
    SurahInfo(index: 90, name: 'البلد', type: 'مكية', verseCount: 20),
    SurahInfo(index: 91, name: 'الشمس', type: 'مكية', verseCount: 15),
    SurahInfo(index: 92, name: 'الليل', type: 'مكية', verseCount: 21),
    SurahInfo(index: 93, name: 'الضحى', type: 'مكية', verseCount: 11),
    SurahInfo(index: 94, name: 'الشرح', type: 'مكية', verseCount: 8),
    SurahInfo(index: 95, name: 'التين', type: 'مكية', verseCount: 8),
    SurahInfo(index: 96, name: 'العلق', type: 'مكية', verseCount: 19),
    SurahInfo(index: 97, name: 'القدر', type: 'مكية', verseCount: 5),
    SurahInfo(index: 98, name: 'البينة', type: 'مدنية', verseCount: 8),
    SurahInfo(index: 99, name: 'الزلزلة', type: 'مدنية', verseCount: 8),
    SurahInfo(index: 100, name: 'العاديات', type: 'مكية', verseCount: 11),
    SurahInfo(index: 101, name: 'القارعة', type: 'مكية', verseCount: 11),
    SurahInfo(index: 102, name: 'التكاثر', type: 'مكية', verseCount: 8),
    SurahInfo(index: 103, name: 'العصر', type: 'مكية', verseCount: 3),
    SurahInfo(index: 104, name: 'الهمزة', type: 'مكية', verseCount: 9),
    SurahInfo(index: 105, name: 'الفيل', type: 'مكية', verseCount: 5),
    SurahInfo(index: 106, name: 'قريش', type: 'مكية', verseCount: 4),
    SurahInfo(index: 107, name: 'الماعون', type: 'مكية', verseCount: 7),
    SurahInfo(index: 108, name: 'الكوثر', type: 'مكية', verseCount: 3),
    SurahInfo(index: 109, name: 'الكافرون', type: 'مكية', verseCount: 6),
    SurahInfo(index: 110, name: 'النصر', type: 'مدنية', verseCount: 3),
    SurahInfo(index: 111, name: 'المسد', type: 'مكية', verseCount: 5),
    SurahInfo(index: 112, name: 'الإخلاص', type: 'مكية', verseCount: 4),
    SurahInfo(index: 113, name: 'الفلق', type: 'مكية', verseCount: 5),
    SurahInfo(index: 114, name: 'الناس', type: 'مكية', verseCount: 6),
  ];
}
